<h1>Add a Meetup</h1>
<p class="lead">Here you can add a new Meetup</p>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-body">
            <?php
            $form = $this->form; /* @var $form \Zend\Form\Form */
            ?>

            <?= $this->form()->openTag($form); ?>
            <div class="form-group">
                <?= $this->formLabel($form->get('title')); ?>
                <?= $this->formElement($form->get('title')); ?>
                <span class="error"><?= $this->formElementErrors($form->get('title'));?></span>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('description')); ?>
                <?= $this->formElement($form->get('description')); ?>
                <span class="error"><?= $this->formElementErrors($form->get('description'));?></span>

            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('date_debut')); ?>
                <?= $this->formElement($form->get('date_debut')); ?>
                <span class="error"><?= $this->formElementErrors($form->get('date_debut'));?></span>

            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('date_fin')); ?>
                <?= $this->formElement($form->get('date_fin')); ?>
                <span class="error"><?= $this->formElementErrors($form->get('date_fin'));?></span>
            </div>


            <div class="form-group">
                <?= $this->formInput($form->get('submit')) ?>
            </div>

            <?= $this->form()->closeTag($form); ?>
        </div>
    </div>
</div>
